### PR TITLE
Nav Detection Setup, Bug Fixes and Improvements

### PR DESCRIPTION
**Pull request by DylDevs**
Full poll request changelog:

- Add nav detection to first time setup 
- Add button in ScreenCapturePlacement to Reload the app, open NavDetctionSetup, or Opn UFLDInstaller
- Create Nav Detection setup panel
- Disabled UI on UFLLD Lane Detection and UFLD Draw Lanes
- Added Theme to first screen in the installer 
- Made "Wating for ETS2 connection..." window unclosable 
- Minor bug fixes with LSTR and UFLD selection in First Time Setup
- Added port selection to ExternalAPI 
- Removed space in requirements.txt 
- Evdev Controller exception wont be raised if the OS is not Linux 
- Added Installer for UFLD

The updates are ready to be pushed after 29 commits (Finally)!

### CODE REVIEW

**Comment by DylDevs** [comment]
Setup is taking awhile to finish because I am having padding issues. Should be done 
~ 1-2 days

**Comment by Tumppi066** [comment]
No worries, take your time :D

**Comment by DylDevs** [comment]
Now I have to figure out 2.0x gonna take even longer. RIP

**Comment by DylDevs** [comment]
This is my current changelog (Not all changes have been commited):
- Add nav detection to first time setup
- Create Nav Detection setup panel
- Disabled UI on UFLLD Lane Detection and UFLD Draw Lanes (There was only the example plugin UI)
- Added Theme to first screen in the installer
- Made "Wating for ETS2 connection..." window unclosable

**Comment by DylDevs** [comment]
Im gonna be starting to roll out a bunch of commits, Nav Detection Setup is sadly still not done yet

**Comment by DylDevs** [comment]
That took longer than it should've XD

**Comment by DylDevs** [comment]
I still have yet to get Navigation Detection Setup fully working
RIP

**Comment by DylDevs** [comment]
Full poll request changelog:

- Add nav detection to first time setup 
- Add button in ScreenCapturePlacement to Reload the app, open NavDetctionSetup, or Opn UFLDInstaller
- Create Nav Detection setup panel
- Disabled UI on UFLLD Lane Detection and UFLD Draw Lanes
- Added Theme to first screen in the installer 
- Made "Wating for ETS2 connection..." window unclosable 
- Minor bug fixes with LSTR and UFLD selection in First Time Setup
- Added port selection to ExternalAPI 
- Removed space in requirements.txt 
- Evdev Controller exception wont be raised if the OS is not Linux 
- Added Installer for UFLD

The updates are ready to be pushed (Finally)!

**Pull request merged**
